### PR TITLE
Add game template, and constants file

### LINKED ISSUE #14: Add game template
This can be from Arcade's website and should likely use the PyMunk physics engine, since it's the most flexible.

### PR DESCRIPTION
**Pull request by brodycritchlow**
Closes #14 

I also added a `constants.py`, to save us some time. I know we did that later in Pyweek35, and it causes some issues.

### CODE REVIEW

**Comment by Anonymous4045** [comment]
Instead of making a fork, could you put this as a repo branch?

**Comment by brodycritchlow** [comment]
> Instead of making a fork, could you put this as a repo branch?

I did try to do that, said I was unauthorized. Maybe it was the way I was doing it on phone? I can redo the PR on PC if thats a problem.

**Review by Anonymous4045 — CHANGES_REQUESTED** [review]
It's a start, however I'd like this to also have blocks, physics, the player movement, etc. There's lots of tutorials that we can use to get there. Let me know if you don't have time and I can work on it.

**Comment by brodycritchlow** [comment]
> It's a start, however I'd like this to also have blocks, physics, the player movement, etc. There's lots of tutorials that we can use to get there. Let me know if you don't have time and I can work on it.

Sounds good, Ill work on the changes tonight.

**Comment by brodycritchlow** [comment]
Moved to #27

**Pull request closed without merging**
